// ============================================================
// FILE: PostMapper.java
// This is a "Mapper" interface created with MapStruct.
// Its job is to convert (map) data between different formats:
//
//   1. PostRequest (DTO from client)  →  Post (database entity)
//   2. Post (database entity)          →  PostResponse (DTO to client)
//   3. PostRequest (update data)       →  existing Post (partial update)
//
// MapStruct generates the implementation code automatically
// at compile-time, so you don't have to write boring
// "post.setTitle(request.title())" boilerplate manually.
// ============================================================
package com.example.crud.post;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/**
 * ---------------------------------------------------------------
 * POST MAPPER (MapStruct)
 * ---------------------------------------------------------------
 * The "componentModel = spring" setting means MapStruct will
 * create a Spring Bean (@Component) so we can inject it wherever
 * we need (e.g., in PostService).
 *
 * Each @Mapping annotation tells MapStruct how to handle fields
 * where the source and target names are different, or where
 * we want to ignore certain fields.
 */
@Mapper(componentModel = "spring")
public interface PostMapper {

    /**
     * Converts a Post (database entity) into a PostResponse
     * (DTO for sending to the client).
     *
     * The tricky part: Post has "author" (a User object), but
     * PostResponse has "authorUsername" (a String).
     * This mapping tells MapStruct to get the username from
     * post.author.username.
     *
     * @param post The entity loaded from the database.
     * @return A PostResponse ready to be serialized to JSON.
     */
    @Mapping(target = "authorUsername", source = "author.username")
    PostResponse toResponse(Post post);

    /**
     * Converts a PostRequest (from the client) into a new Post
     * entity that can be saved to the database.
     *
     * We ignore these fields because:
     *   - "author"    → Will be set manually from the logged-in user.
     *   - "createdAt" → Set automatically by @PrePersist in Post.java.
     *   - "id"        → Auto-generated by the database.
     *   - "updatedAt" → Set automatically by @PrePersist/@PreUpdate.
     *
     * @param request The data received from the client.
     * @return A new Post entity (without author/timestamps yet).
     */
    @Mapping(target = "author", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Post toEntity(PostRequest request);

    /**
     * Updates an EXISTING Post entity with new data from a
     * PostRequest (used for PUT / update operations).
     *
     * The @MappingTarget annotation means "modify this existing
     * object instead of creating a new one."
     *
     * @param request The new data from the client.
     * @param post    The existing Post entity to update.
     */
    @Mapping(target = "author", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateEntity(PostRequest request, @MappingTarget Post post);
}